apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: simpleapiop
  namespace: cp4i
spec:
  barURL: ''
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-AMYG-BQ2E4U
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        image: >-
          image-registry.openshift-image-registry.svc:5000/cp4i/ace-app:latest
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0